security:
    basic:
        enabled:false
management:
    security:
        enabled=false

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761, http://localhost:8861

